### ISSUE TITLE
Docker - browsers fail to launch when not headless

### ISSUE THREAD

**Issue by SchnockNicolas** [mozilla/OpenWPM#474] opened 2019-08-24 13:37 UTC
Hi, I still got the same error from Docker on mac OS (10.13.6) : https://github.com/mozilla/OpenWPM/issues/425  If was closed, but the solution didn't work for me.

I followed instructions https://github.com/mozilla/OpenWPM#running-measurements-from-inside-the-container 

Version of Docker version 2.1.0.0

```
BrowserManager       - INFO     - BROWSER 1: Launching browser...
BrowserManager       - INFO     - BROWSER 2: Launching browser...
BrowserManager       - ERROR    - BROWSER 2: Crash in driver, restarting browser manager
Traceback (most recent call last):
  File "/opt/OpenWPM/automation/BrowserManager.py", line 410, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/opt/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 15, in deploy_browser
    manager_params, crash_recovery)
  File "/opt/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 186, in deploy_firefox
    firefox_options=fo, log_path=interceptor.fifo)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: invalid argument: can't kill an exited process
```

A third iteration gave another error :

```BrowserManager       - ERROR    - BROWSER 2: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: False  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
TaskManager          - CRITICAL - Browser spawn failure during TaskManager initialization, exiting...
Traceback (most recent call last):
  File "/opt/OpenWPM/demo.py", line 37, in <module>
    manager = TaskManager.TaskManager(manager_params, browser_params)
  File "/opt/OpenWPM/automation/TaskManager.py", line 144, in __init__
    self._launch_browsers()
  File "/opt/OpenWPM/automation/TaskManager.py", line 182, in _launch_browsers
    self.close()
  File "/opt/OpenWPM/automation/TaskManager.py", line 565, in close
    self._shutdown_manager()
  File "/opt/OpenWPM/automation/TaskManager.py", line 260, in _shutdown_manager
    browser.shutdown_browser(during_init)
  File "/opt/OpenWPM/automation/BrowserManager.py", line 358, in shutdown_browser
    self.close_browser_manager()
  File "/opt/OpenWPM/automation/BrowserManager.py", line 266, in close_browser_manager
    self.kill_browser_manager()
  File "/opt/OpenWPM/automation/BrowserManager.py", line 312, in kill_browser_manager
    self.crawl_id, self.browser_manager.pid,
AttributeError: 'NoneType' object has no attribute 'pid'
```

Thanks for your help

**Comment by motin** [comment] 2019-08-28 08:23
The error message is rather obscure (I wonder if the log file includes more info?), but in the end I can't reproduce the same error messages. I followed the same instructions including setting up XQuartz etc (linked in the parts after "Instruction on how to run Docker GUI applications in Mac OSX").

```
docker build -f Dockerfile -t openwpm .
./run-on-osx-via-docker.sh python demo.py
```

The three Linux Firefox browsers opens up and the crawls runs, but an error is reported on every run:
```
BrowserManager       - INFO     - BROWSER 1: EXECUTING COMMAND: ('GET', 'http://www.example.com', 3, 1)
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: ('GET', 'http://www.princeton.edu', 3, 2)
BrowserManager       - INFO     - BROWSER 3: EXECUTING COMMAND: ('GET', 'http://citp.princeton.edu/', 3, 3)
BrowserManager       - ERROR    - BROWSER 2: WebDriverException while executing command
Traceback (most recent call last):
  File "/opt/OpenWPM/automation/BrowserManager.py", line 485, in BrowserManager
    browser_params, manager_params, extension_socket)
  File "/opt/OpenWPM/automation/Commands/command_executor.py", line 15, in execute_command
    extension_socket=extension_socket)
  File "/opt/OpenWPM/automation/Commands/browser_commands.py", line 139, in get_website
    close_other_windows(webdriver)
  File "/opt/OpenWPM/automation/Commands/browser_commands.py", line 72, in close_other_windows
    main_handle = webdriver.current_window_handle
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 711, in current_window_handle
    return self.execute(Command.W3C_GET_CURRENT_WINDOW_HANDLE)['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
InvalidSessionIdException: Message: Tried to run command without establishing a connection

TaskManager          - INFO     - BROWSER 2: Received failure status while executing command: GET
BaseAggregator       - INFO     - Received shutdown signal!
```

Upon inspection, we forgot to add ` --shm-size=2g` to the `run-on-osx-via-docker.sh` script. With that change, the crawl runs fine without any error / crash.

**Comment by birdsarah** [comment] 2020-05-13 23:29
I believe this issues is now fixed, can we close @vringar?

**Comment by vringar** [comment] 2020-05-14 12:08
I believe so yes, but I would like to just try it out, by running a headful (?) browser in a container without xhost configured correctly to make sure everything works as expected

**Comment by englehardt** [comment] 2020-09-11 22:29
@vringar ping on this

**Closed** 2020-09-17 09:26 UTC
Labels: bug
