### ISSUE TITLE
Loading a profile in a stateless crawl doesn't seem to work

### ISSUE THREAD

**Issue by Scrashdown** [mozilla/OpenWPM#790] opened 2020-11-12 11:35 UTC
Hello,

I am trying to run a stateless crawl with a seed profile that I created myself, following the [instructions](https://github.com/mozilla/OpenWPM/blob/master/docs/Configuration.md#load-a-profile). When running the crawl, OpenWPM reports it did get an input profile tar file and is loading it:

```
========== Input profile tar files ==========
{
  "2": "/home/loic/Desktop/"
}
```

```
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 4 on browser with id 2
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: GetCommand(http://www.example.com,3)
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: FinalizeCommand(5)
TaskManager          - INFO     - Finished working on CommandSequence with visit_id 4 on browser with id 2
CommandSequence http://www.example.com done
BrowserManager       - INFO     - BROWSER 2: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 2: Launching browser...
deploy_firefox       - INFO     - BROWSER 2: Loading initial browser profile from: /home/loic/Desktop/
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 5 on browser with id 2
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: GetCommand(http://www.princeton.edu,3)
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: FinalizeCommand(5)
TaskManager          - INFO     - Finished working on CommandSequence with visit_id 5 on browser with id 2
CommandSequence http://www.princeton.edu done
BrowserManager       - INFO     - BROWSER 2: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 2: Launching browser...
deploy_firefox       - INFO     - BROWSER 2: Loading initial browser profile from: /home/loic/Desktop/
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 6 on browser with id 2
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: GetCommand(http://citp.princeton.edu/,3)
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: FinalizeCommand(5)
TaskManager          - INFO     - Finished working on CommandSequence with visit_id 6 on browser with id 2
```

But looking at the browser windows, it seems the profile was not loaded correctly. I created this profile with some bookmarks, some browsing history and some changed FF settings to make it easily recognizable, but none of these modifications are visible in the windows spawned by OpenWPM. See images below:

FFDE with expected profile:

![expected](https://user-images.githubusercontent.com/14946298/98934986-23b25d00-24e3-11eb-8b5e-721780966b1c.png)

OpenWPM FF Nightly actual result:

![actual](https://user-images.githubusercontent.com/14946298/98935057-3dec3b00-24e3-11eb-8178-f02b4db872e7.png)

To perform this test, I modified the `demo.py` file. I added the following lines in the loop that changes browser settings:

```Python
# Add browser profile
browser_params[i]["seed_tar"] = '/home/Desktop/'
# Display window so I can check which profile is used
browser_params[i]["display_mode"] = 'native'
```

and removed this line:

```Python
# Launch only browser 0 headless
browser_params[0]["display_mode"] = "headless"
```

But otherwise changed nothing. As we can see in the line

```Python
command_sequence = CommandSequence.CommandSequence(
        site,
        reset=True,
        callback=lambda success, val=site: print("CommandSequence {} done".format(val)),
)
```

`reset` is set to `True`, as it should be according to the instructions.

About the profile itself, I created it by creating a new profile in my own install of FFDE, tar'ed its directory, moved the tar archive to the directory I supplied to the `seed_tar` browser parameter, and renamed it `profile.tar`. As we can see:

```sh
$ ls -alF /home/loic/Desktop/*.tar*
-rw-r--r-- 1 loic loic 18959872 12 nov 12:24 /home/loic/Desktop/profile.tar
```

The file is where OpenWPM expects it to be, and there is no `.tar.gz` file that could maybe be used instead by OpenWPM.

I tested this using the latest commit at the time of me posting this issue: https://github.com/mozilla/OpenWPM/tree/65337e0c19dc857f63bbca1b3aa3773a2c49fd42

**Comment by vringar** [comment] 2020-11-12 14:41
Thank you for this well written and thorough bug report. I'm sorry that the tool isn't working as expected.
Would you have a problem with attaching the profile.tar so I could debug this tomorrow?

**Comment by Scrashdown** [comment] 2020-11-12 21:31
No worries, thank you for your reply. And no problem, you can download it here: https://drive.switch.ch/index.php/s/gf1F4uZqPWjkMJz

**Comment by vringar** [comment] 2020-11-22 11:00
Sorry for falling behind on this.
A couple of things unexpectedly showed up and kept me busy. I'm hoping to get back to this next Wednesday.

**Comment by ksabaa15** [comment] 2021-03-05 07:20
Hello, Is there any update on the bug?

**Comment by boolean5** [comment] 2021-03-05 10:06
Hi @ksabaa15,
I just tried loading a profile using the current master branch and it works as expected.   Please note that now `seed_tar` has to point to the tar file and not to a directory containing the tar file as it used to.

After looking at the tar file @Scrashdown used, I'm pretty sure the reported problem was caused by its directory structure. Specifically, the tar file contains the profile directory itself, when it should only contain the files under it.

To clarify, the structure looks like this:

```
ab26b9fz.PDS-noextension-test/
	--- bookmarkbackups/
        --- crashes/
        --- datareporting/
        ... // more profile files and directories
```

when it should be looking like this:
```
bookmarkbackups/
crashes/
datareporting/
...// more profile files and directories
```

The seed profile files are extracted in a directory under the current profile directory and as a result, the browser ignores them. 

@vringar, I think we can close this now.

**Comment by ksabaa15** [comment] 2021-03-05 10:14
@boolean5 Thank you very much for your time!

**Comment by boolean5** [comment] 2021-03-05 11:08
I suppose we could clarify this a bit in the docs. The wording in `docs/Configuration.md` might be a little misleading: `To load a profile, specify the seed_tar browser parameter in the browser configuration dictionary. This should point to the location of the profile.tar or (profile.tar.gz if compressed) file produced by OpenWPM or by manually tarring a firefox profile directory.`

Changing `by manually tarring a firefox profile directory` to `by manually tarring the contents of a firefox profile directory` could help. @vringar, do you think that would be enough or should we explain this further in the docs?

**Comment by vringar** [comment] 2021-03-11 13:48
I think the issue is prevalent and subtle enough to warrant an explicit paragraph. Maybe we could introduce an extra runtime check to make sure we give an error when trying to load a profile containing only one folder. But idk if the gain from that is bigger than the ensuing complexity.

**Closed** 2021-03-16 13:22 UTC
Labels: bug
