### ISSUE TITLE
Reduce crash rate on .get() in general

### ISSUE THREAD

**Issue by dreisman** [mozilla/OpenWPM#84] opened 2016-09-08 15:00 UTC
Examples of crashes: 

  File "/home/ubuntu/openwpm-census/OpenWPM/automation/BrowserManager.py", line 298, in BrowserManager
    extension_socket)
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/Commands/command_executor.py", line 14, in execute_command
    browser_params=browser_params, extension_socket=extension_socket)
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/Commands/browser_commands.py", line 91, in get_website
    webdriver.get(url)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 245, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 231, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 395, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 426, in _request
    resp = self._conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

**Comment by dreisman** [comment] 2016-09-08 15:05
UnexpectedAlertPresentException: Alert Text: A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://www.sankei.com/apr_comm\u2026v1/common/jquery-1.11.1.min.js:2
Message: Unexpected modal dialog (text: A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

**Comment by englehardt** [comment] 2017-10-09 15:22
Many of these errors are caused by Selenium 2's FirefoxDriver browser extension. With the move to Selenium 3 / Marionette in #152 we should check if the error rate has reduced.

**Comment by englehardt** [comment] 2019-08-06 23:31
Closing in favor of #255 now that we've moved to geckodriver and webextensions.

**Closed by englehardt** 2019-08-06 23:31 UTC
Labels: high-priority, needs-investigation
