### ISSUE TITLE
Document OpenWPM instrumentation and schema

### ISSUE THREAD

**Issue by Zernez** [mozilla/OpenWPM#496] opened 2019-09-29 16:24 UTC
Hello, there is a info file or .py file (some method for insert values) that explain the columns into the tables of the output crawl-data.sqlite? Some columns are difficult to understanding like "frame_id", "parent_frame_id" ecc ecc, in "http_requests" or others. I've searched in "automation" folder all .py files to find some information, and I discover an array "data[]" that cointain some information in "DataAggregator" folder, but with few returns. Thank you.

**Comment by englehardt** [comment] 2019-10-10 04:49
We have some outdated documentation [here](https://github.com/mozilla/OpenWPM/wiki/Instrumentation-Schema-Documentation), but I agree this is sorely needed.

**Comment by vringar** [comment] 2020-01-21 15:15
This seems like a bit of a duplicate of #342

**Comment by englehardt** [comment] 2020-03-13 00:42
> This seems like a bit of a duplicate of #342

Not exactly a duplicate, but I agree the tasks are linked. I've expanded the scope of that bug slightly to include this.

**Closed by englehardt** 2020-03-13 00:42 UTC
Labels: documentation
