### ISSUE TITLE
Remove dependency on localstack / refactor s3aggregator to parquet aggregator

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#652] opened 2020-05-13 20:56 UTC
It's come up in a few issues so gathering the core issue here.

Related: #614, #628 

Localstack has caused us a number of headaches:
* dependency management (needing to pin older versions of libraries)
* upstream changes (#628)
* and generally adding complexity

It's purpose is to mock out s3, but that complexity is driven from the fact that the s3aggregator does two things for structured data:
* aggregates data into parquet
* pushes it to s3

In addition to that it saves out individual content files to s3.
We can separate these two functions allowing for openwpm to generate parquet and then to push it to a variety of locations: s3, gcs, or just local.

**Comment by birdsarah** [comment] 2020-05-13 21:01
@vringar @englehardt I recall from our conversations that the above description of the issue is not accurate and there's an additional piece of related to saving content. Can you update the above description and we can continue iterating the conversation?

**Comment by englehardt** [comment] 2020-05-15 22:16
This seems like a duplicate of #618? We should close that one or the other.

And yes, see https://github.com/mozilla/OpenWPM/pull/390 for context.

Right now we have:

1. S3Aggregator:
    1. structured data: parquet on S3
    2. unstructured data: individual gzipped files on S3 (very inefficient)
2. LocalAggregator:
    1. structured data: sqlite
    2. unstructured data: leveldb

it seems like we want an option to independently choose how to save the structured data (e.g., parquet / sql) from the unstructured data (e.g., leveldb when local and something else when remote).

**Comment by birdsarah** [comment] 2020-05-15 22:28
> it seems like we want an option to independently choose how to save the structured data (e.g., parquet / sql) from the unstructured data (e.g., leveldb when local and something else when remote).

+100

**Comment by birdsarah** [comment] 2020-05-15 22:31
Move from leveldb to rocksdb and use https://github.com/rockset/rocksdb-cloud to push to aws, google cloud etc?

**Comment by birdsarah** [comment] 2020-05-15 22:34
> Move from leveldb to rocksdb and use https://github.com/rockset/rocksdb-cloud to push to aws, google cloud etc?

I don't love this suggestion because I think the path to windows is easier with leveldb.

**Comment by vringar** [comment] 2020-06-29 13:19
One big thing I'd want to be mindful of is the discussion around caching and completion callbacks.
If we offload the caching into an external system we loose the knowledge whether something has been actually saved out to the remote storage or just cached locally.
At least for s3fs I couldn't find a way to manually flush, maybe this happens upon closing the FS?
Also if we cache the records to group them into reasonably sized parquet files and then save them out to s3fs we have a two layered caching system, which doesn't seem ideal to me.

**Closed** 2021-02-22 16:51 UTC

**Comment by birdsarah** [comment] 2021-02-22 17:36
https://giphy.com/gifs/1GrsfWBDiTN60/html5
