### ISSUE TITLE
v0.13.0 process watchdog access error

### ISSUE THREAD

**Issue by MaazBinMusa** [mozilla/OpenWPM#905] opened 2021-04-28 13:46 UTC
I cloned the v0.13.0 from tags as the README said its the stable one.

conda is installed, openwpm env is active but I am getting the following error. I am running on a server that has linux.

I am running with 2 browsers and both are headless.

```
Exception in thread OpenWPM-watchdog:
Traceback (most recent call last):
  File "/home/data/maaz/miniconda3/envs/openwpm/lib/python3.8/site-packages/psutil/__init__.py", line 1174, in _send_signal
    os.kill(self.pid, sig)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/data/maaz/miniconda3/envs/openwpm/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/data/maaz/miniconda3/envs/openwpm/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/data/maaz/XDevice/OpenWPM/openwpm/TaskManager.py", line 272, in _manager_watchdog
    kill_process_and_children(process, self.logger)
  File "/home/data/maaz/XDevice/OpenWPM/openwpm/utilities/multiprocess_utils.py", line 62, in kill_process_and_children
    parent_process.kill()
  File "/home/data/maaz/miniconda3/envs/openwpm/lib/python3.8/site-packages/psutil/__init__.py", line 270, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/data/maaz/miniconda3/envs/openwpm/lib/python3.8/site-packages/psutil/__init__.py", line 1237, in kill
    self._send_signal(signal.SIGKILL)
  File "/home/data/maaz/miniconda3/envs/openwpm/lib/python3.8/site-packages/psutil/__init__.py", line 1184, in _send_signal
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=1308, name='Xvfb')
```

Edit:

turning off process watchdog removes this error

**Comment by vringar** [comment] 2021-04-29 11:26
Interesting. Do you have any other software that's using xvfb on that server?

**Comment by MaazBinMusa** [comment] 2021-04-29 14:01
> Interesting. Do you have any other software that's using xvfb on that server?

I have docker containers running firefox-52 tag of openwpm on the server as well but as far as I know xvfb is not used in headless mode and they are all in headless mode as well.

**Comment by MaazBinMusa** [comment] 2021-04-29 14:09
I was running this without process watch dog and it gave an error on this site

"http://www.cisco.com"

`BrowserManager       - INFO     - BROWSER 4: Launching browser...                                                                                                                                                                                                                                                            BrowserManager       - INFO     - BROWSER 10: Launching browser...                                                                                                                                                                                                                                                           BrowserManager       - INFO     - BROWSER 7: Launching browser...                                                                                                                                                                                                                                                            BrowserManager       - INFO     - BROWSER 5: Launching browser...                                                                                                                                                                                                                                                            BrowserManager       - INFO     - BROWSER 8: EXECUTING COMMAND: FinalizeCommand(5)                                                                                                                                                                                                                                           TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 333 on browser with id 2                                                                                                                                                                                                                 TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 334 on browser with id 6                                                                                                                                                                                                                 BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 6: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: GetCommand(http://www.hola.org,20)
BrowserManager       - INFO     - BROWSER 6: EXECUTING COMMAND: GetCommand(http://www.google.com.vn,20)
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 335 on browser with id 3
BrowserManager       - INFO     - BROWSER 3: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 3: EXECUTING COMMAND: GetCommand(http://www.rubiconproject.com,20)
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 336 on browser with id 9
BrowserManager       - INFO     - BROWSER 9: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 9: EXECUTING COMMAND: GetCommand(http://www.symantec.com,20)
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 337 on browser with id 1
BrowserManager       - INFO     - BROWSER 1: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 1: EXECUTING COMMAND: GetCommand(http://www.duckduckgo.com,20)
TaskManager          - INFO     - Finished working on CommandSequence with visit_id 332 on browser with id 8
CommandSequence http://www.tripadvisor.com done
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 338 on browser with id 5
BrowserManager       - INFO     - BROWSER 5: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 5: EXECUTING COMMAND: GetCommand(http://www.pki.goog,20)
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 339 on browser with id 4
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 340 on browser with id 7
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 341 on browser with id 10
BrowserManager       - INFO     - BROWSER 4: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 7: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 10: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 4: EXECUTING COMMAND: GetCommand(http://www.cisco.com,20)
BrowserManager       - INFO     - BROWSER 7: EXECUTING COMMAND: GetCommand(http://www.slack.com,20)
BrowserManager       - INFO     - BROWSER 10: EXECUTING COMMAND: GetCommand(http://www.amzn.to,20)
FirefoxExtension     - WARNING  - Set visit_id while another visit_id was set
BrowserManager       - INFO     - BROWSER 8: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 8: Launching browser...
TaskManager          - INFO     - Starting to work on CommandSequence with visit_id 342 on browser with id 8
BrowserManager       - INFO     - BROWSER 8: EXECUTING COMMAND: IntitializeCommand()
BrowserManager       - INFO     - BROWSER 8: EXECUTING COMMAND: GetCommand(http://www.theatlantic.com,20)
BrowserManager       - INFO     - BROWSER 6: EXECUTING COMMAND: FinalizeCommand(5)
BrowserManager       - INFO     - BROWSER 3: EXECUTING COMMAND: FinalizeCommand(5)
TaskManager          - INFO     - Finished working on CommandSequence with visit_id 334 on browser with id 6
BrowserManager       - INFO     - BROWSER 5: EXECUTING COMMAND: FinalizeCommand(5)
BrowserManager       - INFO     - BROWSER 6: BrowserManager restart initiated. Clear profile? True
CommandSequence http://www.google.com.vn done
BrowserManager       - INFO     - BROWSER 2: EXECUTING COMMAND: FinalizeCommand(5)
TaskManager          - INFO     - Finished working on CommandSequence with visit_id 335 on browser with id 3
BrowserManager       - INFO     - BROWSER 1: EXECUTING COMMAND: FinalizeCommand(5)
BrowserManager       - INFO     - BROWSER 6: Launching browser...
CommandSequence http://www.rubiconproject.com done
BrowserManager       - INFO     - BROWSER 3: BrowserManager restart initiated. Clear profile? True
BrowserManager       - INFO     - BROWSER 7: EXECUTING COMMAND: FinalizeCommand(5)
BrowserManager       - INFO     - BROWSER 9: EXECUTING COMMAND: FinalizeCommand(5)
TaskManager          - INFO     - Finished working on CommandSequence with visit_id 338 on browser with id 5
CommandSequence http://www.pki.goog done
TaskManager          - INFO     - Finished working on CommandSequence with visit_id 333 on browser with id 2
TaskManager          - INFO     - Finished working on CommandSequence with visit_id 337 on browser with id 1
CommandSequence http://www.hola.org done
CommandSequence http://www.duckduckgo.com done
BrowserManager       - INFO     - BROWSER 4: EXECUTING COMMAND: FinalizeCommand(5)
BrowserManager       - INFO     - BROWSER 5: BrowserManager restart initiated. Clear profile? True
BrowserManager       - ERROR    - BROWSER 4: AssertionError thrown, informing parent and raising
TaskManager          - CRITICAL - BROWSER 4: Received critical error from browser process while executing command FinalizeCommand(5). Setting failure status.
BrowserManager       - ERROR    - BROWSER 10: WebDriverException while executing command`


I am guessing Browser10 crashed because Browser4 raised an error? and browser4 was given the site I mentioned above

**Comment by vringar** [comment] 2021-04-29 14:16
> I have docker containers running firefox-52 tag of openwpm on the server as well 

I can't find that tag on dockerhub. Can you link me to the image you're referring to?

>  xvfb is not used in headless mode and they are all in headless mode as well.

True. This is quite curious.

**Comment by MaazBinMusa** [comment] 2021-04-29 14:18
> > I have docker containers running firefox-52 tag of openwpm on the server as well
> 
> I can't find that tag on dockerhub. Can you link me to the image you're referring to?
> 
> > xvfb is not used in headless mode and they are all in headless mode as well.
> 
> True. This is quite curious.

https://github.com/mozilla/OpenWPM/releases/tag/firefox-52

This is the tag I used to create openwpm image and have been using it.

**Comment by MaazBinMusa** [comment] 2021-04-29 14:26
> Interesting. Do you have any other software that's using xvfb on that server?

I also have a jupyter notebook running on the server that remotely links to my desktop so I can view it here. Is it possible that is using xvfb? even though it is running in the base env whereas this was running in openwpm env

**Comment by vringar** [comment] 2021-04-29 14:35
> https://github.com/mozilla/OpenWPM/releases/tag/firefox-52
> This is the tag I used to create openwpm image and have been using it.

What's your reason for using such an old version of OpenWPM?

**Comment by vringar** [comment] 2021-04-29 14:36
> I also have a jupyter notebook running on the server that remotely links to my desktop so I can view it here. Is it possible that is using xvfb? even though it is running in the base env whereas this was running in openwpm env

I think it's more likely that the different versions of OpenWPM are somehow interfering with each other. Even though Docker should be isolating them against each other...

**Comment by MaazBinMusa** [comment] 2021-04-29 14:42
> > https://github.com/mozilla/OpenWPM/releases/tag/firefox-52
> > This is the tag I used to create openwpm image and have been using it.
> 
> What's your reason for using such an old version of OpenWPM?

This was the last version that supported state-full crawls at the time. I can try rerunning with process_watchdog True once the dockers are all done in a few days.


Also even with the process_watchdog turned off, the crawl crashes as I showed above on "cisco.com". Can you shed some light on that?

**Comment by vringar** [comment] 2021-04-29 15:56
>  Also even with the process_watchdog turned off, the crawl crashes as I showed above on "cisco.com". Can you shed some light on that?

Unfortunately I can't reproduce this error when checking out `v0.13.0` and trying to visit "cisco.com" directly on my local machine.
As a hacky work around I would suggest remove `AssertionError` from 
https://github.com/mozilla/OpenWPM/blob/53e4516930f91b15d5731245ed13b2db1b080a38/openwpm/BrowserManager.py#L541-L547
so that a `BrowserCrashError` gets generated
https://github.com/mozilla/OpenWPM/blob/53e4516930f91b15d5731245ed13b2db1b080a38/openwpm/BrowserManager.py#L131-L132
which gets caught here 
https://github.com/mozilla/OpenWPM/blob/53e4516930f91b15d5731245ed13b2db1b080a38/openwpm/BrowserManager.py#L176-L199
and just leads to the visit getting marked as failed and the BrowserManager restarting.
This way the TaskManager keeps running and the crawl continues.

**Comment by MaazBinMusa** [comment] 2021-04-29 16:19
> > Also even with the process_watchdog turned off, the crawl crashes as I showed above on "cisco.com". Can you shed some light on that?
> 
> Unfortunately I can't reproduce this error when checking out `v0.13.0` and trying to visit "cisco.com" directly on my local machine.
> As a hacky work around I would suggest remove `AssertionError` from
> https://github.com/mozilla/OpenWPM/blob/53e4516930f91b15d5731245ed13b2db1b080a38/openwpm/BrowserManager.py#L541-L547
> 
> 
> so that a `BrowserCrashError` gets generated
> https://github.com/mozilla/OpenWPM/blob/53e4516930f91b15d5731245ed13b2db1b080a38/openwpm/BrowserManager.py#L131-L132
> 
> 
> which gets caught here
> https://github.com/mozilla/OpenWPM/blob/53e4516930f91b15d5731245ed13b2db1b080a38/openwpm/BrowserManager.py#L176-L199
> 
> 
> and just leads to the visit getting marked as failed and the BrowserManager restarting.
> This way the TaskManager keeps running and the crawl continues.

Okay, I will try this. Also was I right in assuming that browser4 caused the crawl to crash? Because browser10 throws the webdriver error as we can see in the logs i posted.

If so, is it because Critical bug crashes the crawl?

**Comment by vringar** [comment] 2021-04-29 16:36
> Also was I right in assuming that browser4 caused the crawl to crash?

Yes, sorry for not stating that earlier.

> Because browser10 throws the webdriver error as we can see in the logs i posted.

Yeah but a webdriver error turns into a BrowserCrashError which is not considered critical and so we don't stop the crawl.

> If so, is it because Critical bug crashes the crawl?

Yes

**Comment by vringar** [comment] 2021-04-30 15:15
Closing this for now.

**Closed by vringar** 2021-04-30 15:15 UTC
