### ISSUE TITLE
Crawl crashes when using multiple browsers

### ISSUE THREAD

**Issue by adrian-hub** [mozilla/OpenWPM#179] opened 2018-03-16 18:26 UTC
Hi, I have been using OpenWPM to do some research and I have been able to understand how it works. I added some commands and I even tweaked the code for minor improvements in my experiments. However, I reached the point I am not able to deal with an issue (sorry I am not a programmer :( ), so please help me.

I am trying to crawl the same website (e.g. www.cnn.com) many times (e.g. 100 times), using the bot_mitigation and dumping the source code recursively. The problem is that platform is crashing when I am using more than 15 browsers (please see the output below). It seems to be that there is a problem with some profile file. Maybe it's a bug? 

Or maybe the platform crashes because there are too many browser instances and it can't handle them and I can't figure out why. 

How can I optimise OpenWPM to use many browsers at the same time? The idea of my experiment is to visit the website at the same time with all the browsers.

```
TaskManager          - INFO     - 

OpenWPM Version: v0.8.0-148-ge2e7dcd
Firefox Version: 52.4.1
========== Manager Configuration ==========
{
  "aggregator_address": [
    "127.0.0.1",
    38775
  ],
  "data_directory": "/home/ubuntu/Desktop/",
  "database_name": "/home/ubuntu/Desktop/crawl-data.sqlite",
  "easylist_path": "/home/ubuntu/Desktop/easylist.txt",
  "failure_limit": null,
  "log_directory": "/home/ubuntu/Desktop/",
  "log_file": "/home/ubuntu/Desktop/openwpm.log",
  "logger_address": [
    "127.0.0.1",
    45070
  ],
  "num_browsers": 20,
  "screenshot_path": "/home/ubuntu/Desktop/screenshots",
  "source_dump_path": "/home/ubuntu/Desktop/sources",
  "testing": false
}

========== Browser Configuration ==========
Keys:
{
  "crawl_id": 0,
  "adblock-plus": 1,
  "bot_mitigation": 2,
  "browser": 3,
  "cookie_instrument": 4,
  "cp_instrument": 5,
  "disable_flash": 6,
  "disconnect": 7,
  "donottrack": 8,
  "extension_enabled": 9,
  "ghostery": 10,
  "headless": 11,
  "http_instrument": 12,
  "https-everywhere": 13,
  "js_instrument": 14,
  "prefs": 15,
  "random_attributes": 16,
  "save_all_content": 17,
  "save_javascript": 18,
  "tp_cookies": 19,
  "tracking-protection": 20,
  "ublock-origin": 21
}

  0  1      2     3        4      5      6      7      8      9     10     11    12    13     14     15    16     17     18     19      20     21
---  -----  ----  -------  -----  -----  -----  -----  -----  ----  -----  ----  ----  -----  -----  ----  -----  -----  -----  ------  -----  -----
  1  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
  2  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
  3  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
  4  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
  5  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
  6  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
  7  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
  8  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
  9  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 10  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 11  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 12  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 13  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 14  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 15  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 16  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 17  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 18  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 19  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False
 20  False  True  firefox  False  False  False  False  False  True  False  True  True  False  False  {}    False  False  False  always  False  False

========== Input profile tar files ==========
  No profile tar files specified

========== Output (archive) profile dirs ==========
  No profile archive directories specified


BrowserManager       - INFO     - BROWSER 3: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/ubuntu/OpenWPM/automation/BrowserManager.py", line 359, in BrowserManager
    with open(ep_filename, 'rt') as f:
IOError: [Errno 2] No such file or directory: '/tmp/rust_mozprofile.CDqwNHQVWlzl/extension_port.txt'

BrowserManager       - ERROR    - BROWSER 3: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: True  | Browser Ready: False 
BrowserManager       - ERROR    - BROWSER 10: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
BrowserManager       - ERROR    - BROWSER 10: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
BrowserManager       - INFO     - BROWSER 10: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/ubuntu/OpenWPM/automation/BrowserManager.py", line 359, in BrowserManager
    with open(ep_filename, 'rt') as f:
IOError: [Errno 2] No such file or directory: '/tmp/rust_mozprofile.3yrW01aEJzDn/extension_port.txt'

BrowserManager       - ERROR    - BROWSER 10: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: True  | Browser Ready: False 
BrowserManager       - INFO     - BROWSER 10: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/ubuntu/OpenWPM/automation/BrowserManager.py", line 359, in BrowserManager
    with open(ep_filename, 'rt') as f:
IOError: [Errno 2] No such file or directory: '/tmp/rust_mozprofile.QEJe8Gy6HpU7/extension_port.txt'

BrowserManager       - ERROR    - BROWSER 10: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: True  | Browser Ready: False 
TaskManager          - CRITICAL - Browser spawn failure during TaskManager initialization, exiting...
Traceback (most recent call last):
  File "demo.py", line 51, in <module>
    manager = TaskManager.TaskManager(manager_params, browser_params)
  File "/home/ubuntu/OpenWPM/automation/TaskManager.py", line 155, in __init__
    self._launch_browsers()
  File "/home/ubuntu/OpenWPM/automation/TaskManager.py", line 210, in _launch_browsers
    self.close()
  File "/home/ubuntu/OpenWPM/automation/TaskManager.py", line 642, in close
    self._shutdown_manager()
  File "/home/ubuntu/OpenWPM/automation/TaskManager.py", line 350, in _shutdown_manager
    browser.shutdown_browser(during_init)
  File "/home/ubuntu/OpenWPM/automation/BrowserManager.py", line 301, in shutdown_browser
    self.kill_browser_manager()
  File "/home/ubuntu/OpenWPM/automation/BrowserManager.py", line 226, in kill_browser_manager
    self.crawl_id, self.browser_manager.pid, self.display_pid,
AttributeError: 'NoneType' object has no attribute 'pid'
```
Thanks.

**Comment by englehardt** [comment] 2018-05-16 22:17
Do things run smoothly when you use less than 15 instances? Are you approaching your machine's memory limits or saturating the CPU? I suspect the problem is related to available resources.

**Comment by englehardt** [comment] 2018-11-20 15:20
Closing this due to lack of follow up.

**Closed by englehardt** 2018-11-20 15:20 UTC
Labels: bug
