### ISSUE TITLE
Error on https://duolingo.com

### ISSUE THREAD

**Issue by sdaitzman** [mozilla/OpenWPM#169] opened 2018-01-19 19:33 UTC
I am trying to run the basic demo code on Duolingo's homepage and I get the following output:

```BrowserManager       - INFO     - BROWSER 22: EXECUTING COMMAND: ('DUMP_PROFILE_COOKIES', 1516389710.674534, 58)
BrowserManager       - INFO     - BROWSER 22: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/openwpm/Desktop/OpenWPM/automation/BrowserManager.py", line 404, in BrowserManager
    browser_params, manager_params, extension_socket)
  File "/home/openwpm/Desktop/OpenWPM/automation/Commands/command_executor.py", line 34, in execute_command
    manager_params=manager_params)
  File "/home/openwpm/Desktop/OpenWPM/automation/Commands/browser_commands.py", line 248, in dump_profile_cookies
    tab_restart_browser(webdriver)  # kills window to avoid stray requests
  File "/home/openwpm/Desktop/OpenWPM/automation/Commands/browser_commands.py", line 100, in tab_restart_browser
    webdriver.execute_script("window.open('')")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 543, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Error: Permission denied to access property "_rollbar_wrapped"
```

Thank you for any help you can offer!

**Comment by sdaitzman** [comment] 2018-01-22 21:31
https://github.com/rollbar/rollbar.js/issues/391

**Comment by englehardt** [comment] 2018-02-16 21:58
Thanks for reporting this and following up with the bug reference! It seems like this is a Firefox 52 (or geckodriver 0.15) issue. Unfortunately the platform will be stuck on these versions until FF 60 ESR is released (May 2018). There will likely be some lag before we upgrade due to the change to WebExtensions (See #148).

**Comment by englehardt** [comment] 2018-02-16 22:13
What's interesting is that the cause of the issue is our call to `window.open` in [browser_commands.py](https://github.com/citp/OpenWPM/blob/63610ca485d160f159babbe6a26634cf1a896083/automation/Commands/browser_commands.py#L100). The rollbar library must overwrite/wrap this function some custom function such that when we call it we end up creating a same origin violation.

We used to send commands [directly to the browser chrome](https://github.com/citp/OpenWPM/blob/683216f7927afc760ba6195479823cd3e23d85df/automation/Commands/browser_commands.py#L56-L69), which would avoid this issue. We had to move away from that during the [upgrade to Selenium 3](https://github.com/citp/OpenWPM/blob/63610ca485d160f159babbe6a26634cf1a896083/automation/Commands/browser_commands.py#L87-L90).

When we upgrade to the next version we should check if this issue still exists and determine whether newer versions of Selenium/geckodriver have better support for sending keypresses to chrome.

**Comment by englehardt** [comment] 2019-08-07 00:12
Closing in favor of #280 .

**Closed by englehardt** 2019-08-07 00:12 UTC
Labels: ESR60-Blocked, bug
